### ISSUE TITLE
rez-selftest failure: test_builds

### ISSUE THREAD

**Issue by elrond79** [nerdvegas/rez#196] opened 2015-05-08 23:09 UTC
When I create a fresh production rez-install, then try to run rez-selftest, I get two failures, both on rez.tests.test_build.TestBuild: test_builds and test_builds_anti

It seems that it builds build_util just fine, then when it tries to build the first thing that relies on it (floob), it gives this error:

```
executing rezbuild.py...
Traceback (most recent call last):
  File "/Volumes/sv-dev01/devRepo/paulm/rez-src/bin/bez", line 2, in <module>
    from rez.cli._bez import run
ImportError: No module named rez.cli._bez
Exit 1
```

On inspecting a bit, it seems that the problem has to do with the way that "parent_variables" are treated.  In essence, it seems like the default behavior is to inherit the parent environment, unless a command tries to use prepend env/append env, in which case the parent environment variable is thrown away, and the var starts fresh with the prepended/appended value.

This is why building of build_util works - because it has no dependencies, nothing tries to "append" to PYTHONPATH, and so it inherits the old pythonpath (so it can import rez); but floob has a dependency on build_util; and since build_util "appends" to PYTHONPATH (which actually wipes it), the context that floob builds in no longer has rez on the PYTHONPATH.

I would expect that PYTHONPATH would either be wiped in both cases, or inherited in both; not wiped in one and inherited in the other.  I can see why it was implemented as it was - it avoids the need to make "arbitrary" decisions about which variables to inherit (or not) when rez "starts". However, this hybrid approach has it's own dangers too: it creates a situation where seemingly innocuous changes in dependent packages can have large (and very non-intuitive / hard to track down) implications for other packages.  ie, package environments become much less self-contained.

Perhaps the clearing of parent variables should be an opt-in behavior, and if you opt in, it clears the variable at the "start", not the first time it's appended / prepended to.  Perhaps PATH and PYTHONPATH could be set to be cleared by default? This seems the best compromise I can think of, between keeping package environments fairly self-contained, minimizing the number of "arbitrary" variable choices, and maintaining behavior relatively close to the current.

**Comment by nerdvegas** [comment] 2015-05-11 17:49
Hey, so there are two separate issues here...

1) The value of PYTHONPATH should not cause this error. 'bez' is one of the rez command line tools - if you have a look at the executable, it's shebanged to 'python -E' (-E ignores PYTHONPATH). This is very deliberate! Rez tools have to work within a rez'd environment, so they have to be completely standalone - in the early days I would run into problems where a rez'd environment containing a different python version to what Rez itself was using, would break the rez tools. Rez is installed into a virtual environment for this reason - the python executable being used is the virtual env's python. I cannot reproduce your error :/ We definitely need to get to the bottom of this, as currently I can't see how this error happened. If you could look into it further that would be great.

2) Rez takes the stance that, if none of the resolved packages touch env var X, then X is not relevant to that environment. There are no special cases (eg PATH etc), all variables are treated equally. I don't think it is unreasonable to say that if no packages use Python, then Rez shouldn't touch PYTHONPATH. After all, Rez != Python... for all I know someone out there could be using Rez in an entirely C++-oriented situation. And you could use this argument (ie Rez should clear certain vars) for lots of vars. Why stop at PATH/PYTHONPATH? Why not LD_LIBRARY_PATH, and the plugin path vars for the various major apps (maya etc) as well?

Having said that, I can see that this feature would help avoid problems in some situations, so I am not against having this as a configurable option, but I do not want to assume any default setting (ie PATH/PYTHONPATH). I think what we could do is generalise the current 'parent_variables' setting. We could replace it with a dict setting, where each entry is a 2-tuple: (variable-name, mode). Mode could be one of: 'inherit', 'unset', 'set' and so on.

PATH is a special case. Unlike other variables, you pretty much can never just decide to unset PATH, because there's always a baseline of tools you expect to be available and are considered outside the scope of rez (ls, bash, etc etc). Currently Rez handles PATH a little differently to other vars for this reason - it does not simply overwrite on first rex append/etc, instead it tries to work out what the minimal PATH setting should be (by starting a simple shell and retrieving $PATH), and appends that to the resulting PATH. So we need to keep this behaviour - although you should also be able to override it, and the 'set' mode is for this - 'set' would just mean, 'set VAR to this value in every shell', and you might want to set this to '/bin:/usr/bin' or something similar.

With that in mind, we should also have an 'inherit_append' mode - inherit the current var value, but append it to the resulting (possibly) new value in the rez'd shell. This mimics current PATH behaviour.

There's some other work that makes sense to do before making this change though. Currently variable changes are not tracked - ie, for any given var (PYTHONPATH let us say) I cannot get a list of packages that altered that variable. We need this feature really - not only is it great for debugging, but also Rez-1 had a feature where it would throw an error if it detected that two or more packages SET the same var, and I'd like to have that back. With this feature, it would be easier to detect if a variable has been changed, in order to determine what rex commands to add to fulfil the mode setting for that variable.

**Comment by elrond79** [comment] 2015-05-12 00:19
> 1) The value of PYTHONPATH should not cause this error. 'bez' is one of the rez command line tools - if you have a look at the executable, it's shebanged to 'python -E' (-E ignores PYTHONPATH). 

So, it seems that the issue is that I already have a version of bez on the path, from my "dev" copy of rez, that lives in my source code repo.  This is what gets found, because PATH isn't wiped (because nothing has yet modified the PATH environment variable), and because RexExecutor.append_rez_path (as the name implies) appends the production-install's bin dir... so my "dev" bez still takes precedence.  And since the non-production-install version of bez does NOT use the "python -E" flag, the PYTHONPATH isn't cleared... and thus the error.

> 2) Rez takes the stance that, if none of the resolved packages touch env var X, then X is not relevant to that environment. There are no special cases (eg PATH etc), all variables are treated equally. I don't think it is unreasonable to say that if no packages use Python, then Rez shouldn't touch PYTHONPATH. After all, Rez != Python... for all I know someone out there could be using Rez in an entirely C++-oriented situation. And you could use this argument (ie Rez should clear certain vars) for lots of vars. Why stop at PATH/PYTHONPATH? Why not LD_LIBRARY_PATH, and the plugin path vars for the various major apps (maya etc) as well?

I agree - having to make arbitrary decisions about different treatment of different variables is an ugly path to go down.  However, I also think it's very likely to trip people up to have this "wipe on first append" behavior.  People simply won't be expecting a method called "append" to actually wipe the variable. And it will lead to a great deal of confusion if package "A" works when used by itself, but then stops working when package "B" is set, when all that package "B" does is append to a bunch of env vars.

Or, consider this scenario: say I have two packages:

```
package A => env.FOOBAR.append("A")
package B => env.FOOBAR.append("B")
```

I would expect the behavior would be the same if I do "rez-env A B" as if I first did "rez-env A", then inside that prompt, did "rez-env B"... however, this is not the case. Instead, we find that:

```
rez-env A B
    $FOOBAR == "A:B"
rez-env A
> rez-env B
    $FOOBAR == "B"
```

I think the simplest solution, that avoids making arbitrary decisions about environment variables, is to have all variables inherit by default, and allow users to add configuration to wipe specific ones.  The other alternative - wiping ALL variables, and allowing inheritence of specific ones - is also a possibility, but seems riskier.

Or, perhaps we could at least have two different methods - append and append_clean (or append_rez)? This would at least be much more discoverable for users.

Now - having said all this... I think it's mostly an issue of non-intuitiveness, and wanting to avoid what I suspect will end up being a common "gotcha"... but once you know the way it works, it's an avoidable issue.  So, from a selfish standpoint, if you still feel strongly we should leave the "wipe-and-append" behavior as it is, I'm not going to push for it anymore.

**Comment by nerdvegas** [comment] 2015-05-12 00:43
Changing the established default behaviour of Rez is not an option, I have an unknown number of existing users and I do not want to suddenly break their working Rez installations. Changing how environment variables are set would definitely do this.

Inheriting all variables by default gets us nothing - in almost all cases, the result is invalid. If I inherit PATH, then I keep tools visible that may not work in the current env. If I inherit PYTHONPATH, I keep python modules visible that may not work in the current env. If I keep <SOMEAPP>_PLUGIN_PATH, I keep plugins visible that may not work in the current env. Why would I have default behaviour that almost guarantees an incorrect result? The whole point of rez is to create an environment that *will* work.

Wiping all variables is not an option. There is no way to determine or assume what scope a particular studio wants Rez to be responsible for. For example, it is very common that SHOW, SEQUENCE, SHOT etc are variables commonly set *before* resolving an environment, that studios definitely do NOT want Rez unsetting.

I think it is enough to have good documentation making clear Rez's default behaviour, and to provide configurable options to change that behaviour for nominated environment variables. While the default behaviour might be a little unexpected to someone new to Rez, it makes sense once you understand the process. And the alternatives - inheriting variables by default or wiping all of them - introduce significant downsides imo.

**Comment by elrond79** [comment] 2015-05-12 19:03
I'm not going to needlessly prolong this discussion with a counterargument, because your tone makes it clear that this is not something that you're open to change (or even debate) on, and I've already stated that I'm willing to live with it as is.

However, while I can now see (or hope, anyway) that you weren't intending to be inflammatory, but were merely frustrated - a feeling I can certainly empathize with - I wanted to point out that statements such as "[t]he whole point of rez is to create an environment that will work" can easily be read as caustically sarcastic, and have little value if the goal is to keep a rational dialogue going.

Again, I can understand the impulse - I've come close to adopting a similar tone in our discussions several times, and may have let some slip through - but I'm hoping that we can both do a better job at keeping the tone civil.  We are both, after all, ultimately working towards the same goal here.

Now, regarding the original error - this should be fixed by the pull request (https://github.com/nerdvegas/rez/pull/197) I made, so, barring any objections to that, we can just merge it, and close this ticket.

**Comment by nerdvegas** [comment] 2015-05-12 21:13
I did not mean for the comment to be sarcastic, nor did I mean to be inflammatory (I'm surprised it comes across this way). I was pointing out that Rez is supposed to provide an environment properly configured for the tools and libraries available within it, which I thought was pretty relevant to the discussion.

Thanks for the PR, I'll have it merged shortly.
A

**Closed** 2015-05-15 18:23 UTC
