### ISSUE TITLE
Error using rez on windows

### ISSUE THREAD

**Issue by bpabel** [nerdvegas/rez#348] opened 2016-09-26 22:09 UTC
I'm trying to build the hello_world example package provided with rez but I'm getting errors just doing the cmake compiler tests that I don't get when just running cmake by itself without rez.

When I run rez-build on the hello_world project, I get the following output:

NOTE: I get this same output even if the `CMakeLists.txt` file only contains the `cmake_minimum_required` command

```
Executing: c:\program files (x86)\cmake\bin\cmake.exe -d C:\Users\babel\workspace\rez\example_packages\hello_world -Wno-dev -DCMAKE_ECLIPSE_GENERATE_S
OURCE_PROJECT=TRUE -D_ECLIPSE_VERSION=4.3 --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX=C:\Users\babel\packages\hello_world\1.0.0 -DCMAKE_MODULE_PATH=%C
MAKE_MODULE_PATH% -DCMAKE_BUILD_TYPE=Release -DREZ_BUILD_TYPE=local -DREZ_BUILD_INSTALL=0 -G NMake Makefiles
Not searching for unused variables given on the command line.
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.6/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
  14.0/VC/bin/cl.exe" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/Users/babel/workspace/rez/example_packages/hello_world/build/CMakeFiles/CMakeTmp



  Run Build Command:"nmake" "/NOLOGO" "cmTC_62b41\fast"

        "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\nmake.exe" -f
  CMakeFiles\cmTC_62b41.dir\build.make /nologo -L
  CMakeFiles\cmTC_62b41.dir\build

  Building C object CMakeFiles/cmTC_62b41.dir/testCCompiler.c.obj

        C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe
  @C:\Users\babel\AppData\Local\Temp\nm7D7D.tmp

  testCCompiler.c

  Linking C executable cmTC_62b41.exe

        "C:\Program Files (x86)\CMake\bin\cmake.exe" -E vs_link_exe
  --intdir=CMakeFiles\cmTC_62b41.dir --manifests --
  C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo
  @CMakeFiles\cmTC_62b41.dir\objects1.rsp
  @C:\Users\babel\AppData\Local\Temp\nm7DDC.tmp

  RC Pass 1 failed to run.

  NMAKE : fatal error U1077: '"C:\Program Files (x86)\CMake\bin\cmake.exe"' :
  return code '0xffffffff'

  Stop.

  NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio
  14.0\VC\bin\nmake.exe"' : return code '0x2'

  Stop.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt


-- Configuring incomplete, errors occurred!
See also "C:/Users/babel/workspace/rez/example_packages/hello_world/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/babel/workspace/rez/example_packages/hello_world/build/CMakeFiles/CMakeError.log".
rez: BuildError: The cmake build system failed
```

However, if I just use `cmake` directly to build the hello_world project, I get this successful output from cmake

NOTE: obviously, I have to remove everything except the `cmake_minimum_required` command from the build file, but the C compiler tests complete succesfully using cmake and not with rez.

```

-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/babel/workspace/rez/example_packages/hello_world
```

**Comment by alexxbb** [comment] 2016-11-20 06:24
I have exact the same problem!
Before calling rez-* i sourced C:\VC\VC\bin\amd64\vcvars64.bat

Invoking cmake build system...
Executing: c:\cmake\bin\cmake.exe -d C:\Users\alex\sandbox\rezolution\testgeo -Wno-dev -DCMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT=TRUE -D_ECLIPSE_VERSION=4.3 --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX=~sandbox\rezolution\dev\testgeo\0.0.1 -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_BUILD_TYPE=Release -DREZ_BUILD_TYPE=local -DREZ_BUILD_INSTALL=0 -G NMake Makefiles
Not searching for unused variables given on the command line.
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/VC/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/VC/VC/bin/amd64/cl.exe -- broken
CMake Error at C:/CMake/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "C:/VC/VC/bin/amd64/cl.exe" is not able to compile a simple
  test program.

  It fails with the following output:

   Change Dir: C:/Users/alex/sandbox/rezolution/testgeo/build/CMakeFiles/CMakeTmp



  Run Build Command:"nmake" "/NOLOGO" "cmTC_c0e07\fast"

        C:\VC\VC\bin\amd64\nmake.exe -f CMakeFiles\cmTC_c0e07.dir\build.make
  /nologo -L CMakeFiles\cmTC_c0e07.dir\build

  Building C object CMakeFiles/cmTC_c0e07.dir/testCCompiler.c.obj

        C:\VC\VC\bin\amd64\cl.exe @C:\Users\alex\AppData\Local\Temp\nmA28F.tmp

  testCCompiler.c

  Linking C executable cmTC_c0e07.exe

        C:\CMake\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_c0e07.dir
  --manifests -- C:\VC\VC\bin\amd64\link.exe /nologo
  @CMakeFiles\cmTC_c0e07.dir\objects1.rsp
  @C:\Users\alex\AppData\Local\Temp\nmA2CF.tmp

  RC Pass 1 failed to run.

  NMAKE : fatal error U1077: 'C:\CMake\bin\cmake.exe' : return code
  '0xffffffff'

  Stop.

  NMAKE : fatal error U1077: 'C:\VC\VC\bin\amd64\nmake.exe' : return code
  '0x2'

  Stop.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt


-- Configuring incomplete, errors occurred!
See also "C:/Users/alex/sandbox/rezolution/testgeo/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/alex/sandbox/rezolution/testgeo/build/CMakeFiles/CMakeError.log".
rez: BuildError: The cmake build system failed!

**Comment by alexxbb** [comment] 2016-11-23 03:09
Ok, the problem is rez-build does not inherit parent environment. For now i come up with just monkey patching source code and passing parent environment to subshell. I know it's bad, and should be done more elegant (suggestions?), but it's fine for now while i'm testing.

**Comment by nerdvegas** [comment] 2016-11-23 03:40
Hi alexxbb,

Rez does inherit the env (unless there's a Windows-specific issue I'm not
aware of), however it does overwrite vars that get pre/appended. I would
like to provide more control over this behavior. Specifically, the most
useful default behavior would be to retain the pre-rez-env value of
variables such as PATH, and append that to the overwritten result within
the rez env.

Thx
A

**Comment by KelSolaar** [comment] 2017-01-11 04:54
Hi,

Experiencing similar issues here, calling `rez-build --install` will fail not finding *CC* nor *CXX*:

```
C:\Program Files (x86)\Microsoft Visual C++ Build Tools>d:

D:\>cd rez-2.2.0

D:\rez-2.2.0>cd example_packages

D:\rez-2.2.0\example_packages>cd hello_world

D:\rez-2.2.0\example_packages\hello_world>rez-build --install

--------------------------------------------------------------------------------
Building hello_world-1.0.0...
--------------------------------------------------------------------------------
Resolving build environment: python
resolved by thomas@MORGOTH.ad.lambda.nz, on Wed Jan 11 17:43:56 2017, using Rez v2.2.0

requested packages:
python
~platform==windows       (implicit)
~arch==AMD64             (implicit)
~os==windows-10.0.14393  (implicit)

resolved packages:
arch-AMD64             C:\Users\thomas\packages\arch\AMD64                                                       (local)
os-windows-10.0.14393  C:\Users\thomas\packages\os\windows-10.0.14393                                            (local)
platform-windows       C:\Users\thomas\packages\platform\windows                                                 (local)
python-2.7.13          C:\Users\thomas\packages\python\2.7.13\platform-windows\arch-AMD64\os-windows-10.0.14393  (local)

Invoking cmake build system...
Executing: d:\applications\cmake-3.7.1-win64-x64\bin\cmake.exe -d D:\rez-2.2.0\example_packages\hello_world -Wno-dev -DCMAKE_ECLIPSE_GENERATE_SOURCE_PROJECT=TRUE -D_ECLIPSE_VERSION=4.3 --no-warn-unused-cli -DCMAKE_INSTALL_PREFIX=C:\Users\thomas\packages\hello_world\1.0.0 -DCMAKE_MODULE_PATH=%CMAKE_MODULE_PATH% -DCMAKE_BUILD_TYPE=Release -DREZ_BUILD_TYPE=local -DREZ_BUILD_INSTALL=1 -G NMake Makefiles
Not searching for unused variables given on the command line.
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error in CMakeLists.txt:
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "D:/rez-2.2.0/example_packages/hello_world/build/CMakeFiles/CMakeOutput.log".
See also "D:/rez-2.2.0/example_packages/hello_world/build/CMakeFiles/CMakeError.log".
rez: BuildError: The cmake build system failed
```
but invoking `cmake .`  successfully manage to locate the compiler(s):

```
D:\rez-2.2.0\example_packages\hello_world>cmake .
-- Building for: NMake Makefiles
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    RezBuild


CMake Error at CMakeLists.txt:6 (rez_install_python):
  Unknown CMake command "rez_install_python".


-- Configuring incomplete, errors occurred!
See also "D:/rez-2.2.0/example_packages/hello_world/CMakeFiles/CMakeOutput.log".

D:\rez-2.2.0\example_packages\hello_world>
```

It would be great to have a solution that does not involve patching the source code.

@alexxbb : Would you mind sharing your work around please?

Cheers,

Thomas

**Comment by nerdvegas** [comment] 2017-01-11 20:31
Hi all,

As you may be aware, I'm leaving rez Windows dev to others. I have an eye
on this thread though, and if a candidate PR is put forward then I'll make
time to get it merged, since this appears to be a problem for a number of
people.

Thanks
Allan

**Comment by KelSolaar** [comment] 2017-01-11 20:47
@nerdvegas (Allan): Are the developers supporting Windows platform aware of that issue? Could they be dragged in the convo?

**Comment by instinct-vfx** [comment] 2017-01-12 11:30
I will have to take a closer look. My initial suspicion would be related to the way rez handles environment variables on windows. How do you make your shell aware of cl when manually running cmake? By running a VS developer shell?

Cheers,
Thorsten

**Comment by assumptionsoup** [comment] 2017-02-09 00:38
I'm not entirely sure how cmake finds cl.  It's not in $PATH.  I think cmake discovers it somehow.  I don't have to do anything special to make cmake find the msbuild compiler in a normal shell.  Only the msbuild bin directory is on the $PATH.

Sorry, I know this isn't particularly helpful.  Is there some way to get rez to print the env vars during `rez-build`?  I can't seem to get it to spit out anything useful.

**Comment by instinct-vfx** [comment] 2017-02-09 08:35
I guess this relates to this thread i started a while back: https://groups.google.com/forum/#!topic/rez-config/psZodWdgrxY

Typically you would call cl from a visual studio prompt. But because rez pulls its PATH etc. Variables from the registry rather than the environment you can not inject into PATH in an existing shell. Well you can, but it will get overwritten. This only happens the first time a package modifies PATH in any way though. Hence can be a bit unpredictable. I'd vote for changing that behavior on windows actually and get all environment variables from the shell. And i am also not sure we really want to trash it completely on first touch.

**Comment by instinct-vfx** [comment] 2017-02-10 08:52
Hey Alan,

i agree, but still think the source for the environment variables should be the calling environment rather than the registry. As using the registry completely strips the possibility to modify the environment prior to launching rez (e.g. to introduce custom path entries without modifying the system).

There is quite a lot of fixes and PRs in regards to windows, some tackle the same issue differently, some do the same thing slightly different or spread out differently in commits/PRs. Would be good to get that all pulled together. I have some time reserved for rez this month. Will see if i can get at least an overview.

**Comment by nerdvegas** [comment] 2017-02-10 21:10
Hey Thorsten, that'd be great as I lack the context to prioritize any of
those overlapping features. I'm actually working on rez at the moment,
hoping to spend a chunk of next week getting on top of some PRs. But if you
can get to a good place with the Windows side of things and bring it into a
single PR, I'll prioritise merging that into master. Just give me a head's
up.

Thx
A


On Fri, Feb 10, 2017 at 7:52 PM, Thorsten Kaufmann <notifications@github.com

**Comment by Kaiserlicht** [comment] 2017-03-24 11:53
So is there a ways to fix this? I have the same problem. Building hello_world with rez fails weil running `cmake .` seems to work....

**Comment by instinct-vfx** [comment] 2017-03-24 20:37
I still have quite a bit of my time blocked for rez atm. "Sadly" most is in regards to designing how we deploy/provide rez itself and sync packages etc.

For packages that need building i am currently using bez wrapping around cmake anyways because i need to call cmake using specific command line options to set target platform etc.

I have yet to actually look into fixing quite a lot of windows related things and propose some changes to the cmdline plugin. But there's only so much time :(

**Comment by nerdvegas** [comment] 2017-03-24 21:31
In case it makes things easier, note that the new rez release contains the
'custom build commands' feature, so you can just exec a python file
directly, which should be cleaner.

Thx
A


On Sat, Mar 25, 2017 at 7:37 AM, Thorsten Kaufmann <notifications@github.com

**Comment by Kaiserlicht** [comment] 2017-03-25 17:18
Thanks guys, I will give Bez a try...

**Comment by willjp** [comment] 2018-04-04 01:06
Hey Guys!

This isn't the most ideal solution yet (running vcvarsall.bat is very slow), but it does fit into rez's workflow, and cmake works as expected. If this is all fairly obvious, I'm sorry. I am new to both rez and software compilation on windows.


# 1) Get a Compiler

You can't compile without a compiler. Firstly, make sure you actually have one.
You can install cmake and the microsoft build tools most easily using [chocolatey](https://chocolatey.org/)).

``` powershell
choco install -y cmake
choco install -y visualstudio2017buildtools
choco install -y visualstudio2017-workload-vctools
```


# 2) Create a vscode Rez Package

Add a package for vscode right in your rez package repository. This package will call `vcvarsall.bat` and set up your cmd.exe's environment variables 

``` powershell
# directory structure:

$env:USERPROFILE\packages\
    vscode\
        x64_2017_14.13.2612\
            package.py
```


`...\vscode\x64_2017_14.13.2512\package.py`
``` python
uuid = 'b9be08860d4e4f32bb5c861fce92f268'
name = 'vscode'
version = 'x64_2017_14.13.2612'

def commands():
    vcvarsall = 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Auxiliary\\Build\\vcvarsall.bat'
    command( '"{}" x64'.format(vsvarsall) )
```



# 3) Create a 2nd Rez Package (one to compile with cmake)
We'll build this package normally using rez-build. Create it somewhere other than your rez package repository.

`2nd Package Structure`
``` bash
package/
    emptyfile.txt         # just something arbitrary to package
    CMakeLists.txt
    package.py
```


`CMakeLists.txt`
``` cmake
cmake_minimum_required(VERSION 3.0)

include(RezBuild)

rez_install_files(
    emptyfile.txt
    DESTINATION .
)
```


`package.py`
``` python
import sys
uuid = '...' # some uuid
name = 'cmaketest'
version = '0.0.a1'

build_requires = []
if sys.platform == 'win32':
    build_requires.append('vscode')
```

# 4) rez-build

Now you can run rez-build, and both cmake and NMake's will run `vcvarsall.bat` , so your path and the myriad of other computer-specific variables required to compile in windows.

``` powershell
cd $your_package
rez-build
```

**Comment by DanGroverUK** [comment] 2018-04-06 16:09
Thanks willjp - you're a lifesaver! One tiny note, though - there's a typo in the line line of your vscode package.py file. You have it listed as...

`command( '"{}" x64'.format(vsvarsall) )`

But naturally it should be...

`command( '"{}" x64'.format(vcvarsall) )`

**Comment by willjp** [comment] 2018-04-06 21:03
Thanks very much! I updated the comment, and I'm very glad it was helpful!!

**Comment by nerdvegas** [comment] 2018-09-06 05:31
Please note this feature, which has now been merged to master and may be relevant here: https://github.com/nerdvegas/rez/pull/454

This gives you the ability to explicitly specify an initial PATH value. Note that it would be better to modify rez's env-var management in general (as discussed earlier), but this may be a decent workaround in the interim.

Thx
A

**Comment by nerdvegas** [comment] 2018-09-06 05:48
To add to this - it seems like a simple fix might be to simply append PATH with the pre-rez-build $PATH. It isn't perfect (it assumes you haven't rez-built within a rez-env'd shell; there'll be potential duplicate paths), but it seems to me that it'd work the large majority of the time. Might be a good cheap fix until better env-var management is a thing. Thoughts?

**Comment by willjp** [comment] 2018-09-20 12:15
I am not experienced at compiling, but that seems like it would make sense. That way before you ran your rez-build you could pass in your vcvarsall.bat arguments. Then you'd still get all of your rez configured paths in front of your original path.

Stealing examples from vcvarsall.bat's help output:
```
vcvarsall.bat x64 8.1
vcvarsallbat x86_arm uwp 10.0.10240
```

I'm not sure if this is useful or relevant to this conversation, but in the end, we moved to bez. We're just using python, and occasionally cx_freeze so we didn't really need all of the power of cmake. 

To make it a little more friendly, I created a bezutils.py file where I reproduced some of the cmake scripts in python, and created a rez-package that could be added to build_requires which added it to the PYTHONPATH.

**Comment by instinct-vfx** [comment] 2018-09-20 12:29
We're using bez (or now custom build commands to be exact) just to call cmake as there are some cmake issues on windows. I want to look into this, currently trying to free up resources to do some rez work.

**Closed** 2020-01-17 07:35 UTC
