### ISSUE TITLE
String Quoting Changes

### ISSUE THREAD

**Issue by mstreatfield** [nerdvegas/rez#189] opened 2015-05-05 06:34 UTC
Hi,

We integrated the most recent changes in resources2 and have hit two problems with string quoting.

1. An alias in an old-style command which was previously reported as:

        some_command "app == \"houdini\" "

    Is now coming back as:

        some_command "app == "houdini" "

2. The unit tests now fail *only* on OSX with:

        ======================================================================
        FAIL: test_rex_code (rez.tests.test_shells.TestShells)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "/private/tmp/jenkins-rez_unit_test_multi_platform-PLATFORM=osx-44/packages/rez/44/lib/python2.7/site-packages/rez-44-py2.7.egg/rez/tests/util.py", line 88, in wrapper
            func(self, *args, **kwargs)
          File "/private/tmp/jenkins-rez_unit_test_multi_platform-PLATFORM=osx-44/packages/rez/44/lib/python2.7/site-packages/rez-44-py2.7.egg/rez/tests/test_shells.py", line 266, in test_rex_code
            _execute_code(_rex_assigning, expected_output)
          File "/private/tmp/jenkins-rez_unit_test_multi_platform-PLATFORM=osx-44/packages/rez/44/lib/python2.7/site-packages/rez-44-py2.7.egg/rez/tests/test_shells.py", line 203, in _execute_code
            self.assertEqual(output, expected_output)
        AssertionError: Lists differ: ['ello', 'ello', 'ello', '\\\\... != ['ello', 'ello', 'ello', '\\',...

I'm still trying to narrow down which change might have introduced - has there been any changes to the way string quoting is handled recently?  We pulled down about a hundred commits so it's taking a while so a shortcut would be appreciated!

**Comment by nerdvegas** [comment] 2015-05-05 14:28
Hey mark,

Yeah there's a recent small change to fix a bug I hit in old style commands conversion, will look into it soon as I get to work..
A

**Comment by nerdvegas** [comment] 2015-05-05 15:09
Ps - I don't know what would account for the quoting change on osx.. The change I'm thinking of was only in convert_old_commands.

**Comment by nerdvegas** [comment] 2015-05-05 18:59
Hey @mstreatfield,

I *think* the culprit is this in convert_old_commands:

```
    def _encode(s):
        s = s.replace('\\"', '"')
        return repr(s)
```

..but I'm confused because that backslash removal has been there a long time (the repr is part of the recent change).

What would be the fix here? Iirc the backslash removal is there because of existing old commands like so:

```
export FOO=\"hey there\"
```

Here we remove the slashes because the new string quoting takes care of things. But in the example you cite, you actually do need the backslashes - even in Rex (I tested it) - because you have a quotes within quotes situation going on.

So I'm both unclear on when the behaviour would have changed, and what the fix should be. I suspect there are many potential edge cases in old code conversion - the question is where do we draw the line and just say to convert your package to py instead (using rez-yaml2py) and fix the resulting rex code by hand?

Sorry I couldn't be of more help, let me know if you find more,
A

**Comment by mstreatfield** [comment] 2015-05-06 03:38
I checked this a bit more.  The following is tested in bash always using a package.yaml file.  The alias is being specified as:

    commands:
    - alias foo='command --option "bar == \"maya\" "'

Before the recent update to Rez, this would set an alias:

    BASH_FUNC_foo()=() {  command --option "bar == \"maya\" " }

However now that same alias is:

    BASH_FUNC_foo()=() {  command --option "bar == "maya" " }

Interesting a command that is defined in a similar way to the alias:

    commands:
    - export BAR="$BAR function(\"spam\")"

Is still set correctly, regardless of the Rez version:

    > echo $BAR
    BAR=function("spam")

So that change has only affected the alias.  

As well as the introduction of `repr` didn't there also used to be a call to `s.encode("string-escape")` somewhere around there?

> Where do we draw the line and just say to convert your package to py instead

I think if you want to do something that wasn't previously well supported by `convert_old_commands` then yes, the option is to switch to a .py file.  I think the difference in this case is that it used to work, it is (as far as I am aware) a valid bash command (which was supported in Rez 1) that now doesn't work.

**Comment by nerdvegas** [comment] 2015-05-06 06:01
I'll dig up the command conversion that was failing for us and compare the two.. It's probably a case of fixing one bug and creating another.
A

**Comment by nerdvegas** [comment] 2015-05-07 18:52
Ok, I think I see the source of the problem. But the issue wasn't introduced recently - I went back past my recent change and I still see the issue (talking about the alias example here).

So initially we needed to convert old commands like this:

```
- export VARIABLE_WITH_QUOTES="loadPlugin(\"mayaPlugin\")"
```

The \" escaping is valid for sh, but not other shells. To dead with this, convert_old_commands is first removing the bookend quotes("), then replacing \" with ", then running shell-specific escape_string() on the result. All good.

However, we run into a problem if we have quoting too many levels deep, such as in your alias example. And the problem isn't unique to alias, nor to convert_old_commands - I think we've uncovered a more general issue.

Basically, the escape_string() functions are not clever enough to detect quotes within quotes ad infinitum - in these cases the shell-specific escaping would have to be applied more than once depending on the level of nesting. But also, all escape_string() sees is the string you've given it - with bash-specific escaping! 

In other words, in rex we can do this:

```
info('hey "there" ')
```

But how do we provide a string with further quoting, in a shell-agnostic way? eg:

```
info('hey "there \\"you\\" " ')
```
What we've inadvertently done is used bash-style quote escaping because we have no other way of expressing what we want. And the various escape_string() implementations have no choice but to convert the string they're given. So this kind of nested quoting will work fine for sh-like shells, but will not give the expected result on say, csh.

I can "fix" the immediate problem by making the removal of \" cleverer in convert_old_commands(). But the bigger problem would be much more complicated to fix I think. We'd need to be able to interpret the string coming from rex, break it down based on string escaping (adopting the bash style escaping as the syntax we understand) and then reconstructing the shell-specific string with multiple calls to escape_string(), so that double/triple/etc escaping occurs on nested quotes. 

It's horribly complicated, my brain hurts thinking about it. We probably just have to accept the fact that complicated quote escaping scenarios are shell-specific, and we'll just have to work around that if and when we have a combo of a package consumed in multiple shells, containing complex quoting. I don't think we expose the shell type to rex right now, but maybe we should in anticipation of this problem.

**Comment by nerdvegas** [comment] 2015-05-07 19:03
To expand on the alias example - the issue is also that there is ambiguity - rex cannot know whether you mean to use the literal string given, or if you intend the inner quotes to be escaped according to the target shell. To add enough contextual info to guarantee correct interpretation by the shell, we'd have to introduce a new type to represent strings in rex, that can express that there are substrings present that require further escaping. And that just sounds too complicated for people to want to use at all.

**Comment by nerdvegas** [comment] 2015-05-07 19:06
Last comment. Expanding again on the previous comment, I guess we could expose an 'expand_string' function in rex, which is actually bound to the target shell. Thus you could do:

```
alias(command, 'foo "hey %s" ' % expand_string('"there"'))
```

**Comment by nerdvegas** [comment] 2015-05-07 22:14
Hey @mstreatfield,

I've pushed a fix for this. It avoids removing escaping quote slashes if that part of the string is already within quotes. In other words this should fix the issue with the alias example you've given. See 'string_quoting_may07' branch, and let me know if that works.

Thx
A

**Comment by mstreatfield** [comment] 2015-05-14 06:37
Thanks - that seems to do the trick.  

We have a set of integration tests that compare a whole set of production environments for two different rez versions on both tcsh and bash (as well as running the unit tests on windows, centos and osx).  And they are now much happier!

Curiously the OSX test failures have now stopped (even before I cherry picked this change) - not sure what was up there.

**Comment by nerdvegas** [comment] 2015-05-15 23:16
Merged fix, closing.

**Closed by nerdvegas** 2015-05-15 23:16 UTC
